main/forms/login.py
from flask_wtf import FlaskForm
from wtforms import validators, PasswordField, SubmitField, RadioField
from wtforms.fields.html5 import EmailField

class Login(FlaskForm):

    email = EmailField(
        label="E-Mail",
        validators=[validators.DataRequired(message="Este campo es requerido"),
            validators.Email(message="Formato incorrecto")],
        render_kw={"placeholder": "Username"})
    password = PasswordField(
        label="Contraseña",
        validators=[
            validators.DataRequired(message="Este campo es requerido")],
        render_kw={"placeholder": "Password"})
    submit_button = SubmitField(label="Ingresar")

class Register(FlaskForm):

    email = EmailField(
        label="",
        validators=[
            validators.DataRequired(message="Este campo es obligatorio"),
            validators.EqualTo("re_email", message="Los email deben ser iguales"),
            validators.Email(message="Formato incorrecto")],
        render_kw={"placeholder": "Email"})
    re_email = EmailField(
        label="",
        validators=[
            validators.DataRequired(message="Este campo es obligatorio"),
            validators.Email(message="Formato incorrecto")],
        render_kw={"placeholder": "Repetir Email"})
    password = PasswordField(
        label="",
        validators=[
            validators.DataRequired(message="Este campo es obligatorio"),
            validators.EqualTo("re_password", message="Las contraseñas deben ser iguales")],
        render_kw={"placeholder": "Contraseña"})
    re_password = PasswordField(
        label="",
        validators=[
            validators.DataRequired(message="Este campo es obligatorio")
        ],
        render_kw={"placeholder": "Repetir contraseña"})
    admin_choices = [(1, 'Si'), (0, 'No')]
    admin = RadioField(
        label="",
        validators=[validators.InputRequired(message="Este campo es obligatorio")],
        choices=admin_choices,
        coerce=int)
    submit_button = SubmitField(label="Registrarse")

main/routes/config.py
import json
from flask import Blueprint, render_template
import flask_login
from flask_login import login_required
from main import admin_required
from flask import Blueprint, render_template, request, url_for, current_app
from main.resources.auth import LoggedUser
import requests
from werkzeug.utils import redirect
from main.forms.Parking import CreateParking

config = Blueprint('config', __name__, url_prefix='/')


@config.route('/config', methods=['POST', 'GET'])
@login_required
def index():
    if flask_login.current_user.admin:
        auth = request.cookies['access_token']
        headers = {
            'content-type': "application/json",
            'authorization': "Bearer " + auth
        }
        url = str(current_app.config['API_URL']) + str('/user/' + str(flask_login.current_user.id))
        r = requests.get(url=url)
        try:
            form_setup = CreateParking()
            if json.loads(r.text)['parkingId'] == None:
                if form_setup.validate_on_submit():
                    url = str(current_app.config['API_URL']) + str('/parking/add')
                    data = {
                        "name": form_setup.name.data,
                        "location": form_setup.location.data,
                        "space": form_setup.space.data,
                        "price": form_setup.price.data,
                        "rate": 0,
                        "config": "",
                        "userId": flask_login.current_user.id
                    }
                    r = requests.post(url=url, headers=headers, json=data)
                    parkingId = json.loads(r.text)["parkingId"]
                    url = str(current_app.config['API_URL']) + str('/generateqr/' + str(parkingId))
                    requests.get(url=url, headers=headers)
                    data = {
                        "parkingId": parkingId
                    }
                    requests.put(current_app.config['API_URL'] + "/user/" + str(flask_login.current_user.id), headers=headers, data=json.dumps(data))
                    return redirect(url_for('index.index'))
                return render_template('setup.html', current_user=flask_login.current_user, form_setup=form_setup)
            else:
                r = requests.get(current_app.config['API_URL'] + "/parking/" + str(json.loads(r.text)['parkingId']), headers=headers)
                form_setup.name.data = json.loads(r.text)['name']
                form_setup.location.data = json.loads(r.text)['location']
                form_setup.space.data = json.loads(r.text)['space']
                form_setup.price.data = json.loads(r.text)['price']
                # Verificar si guardado los cambios
                return render_template('setup.html', current_user=flask_login.current_user, form_setup=form_setup)
        except Exception as e:
            print(e)
    else:
        # Aca debo traer los datos de usuario
        return render_template('config-user.html', current_user=flask_login.current_user)

main/routes/home.py
import json
import datetime
from flask import Blueprint, render_template
import flask_login
from flask_login import login_required
from flask import Blueprint, render_template, request, url_for, current_app, make_response
from main.resources.auth import LoggedUser
from sphinx.util import requests

home = Blueprint('index', __name__, url_prefix='/')


@home.route('/')
@home.route('/index', methods=['POST', 'GET'])
@login_required
def index():
    if flask_login.current_user.admin:
        return render_template('home.html', current_user=flask_login.current_user)
    else:
        if request.method == 'POST':
            location = request.form['location']
            resp = make_response(render_template('home-common.html'))
            expire_date = datetime.datetime.now()
            expire_date = expire_date + datetime.timedelta(hours=1)
            resp.set_cookie('location', location, expires=expire_date)
            return resp
        location = request.cookies.get('location')
        if location != None:
            url = str(current_app.config['API_URL']) + '/parkings/' + location + '&' + '5000'
            r = requests.get(url=url)
            parkings = json.loads(r.text)['parkings']
            return render_template('home-common.html', current_user=flask_login.current_user, parkings=parkings)
        else:
            return render_template('capture-location.html', current_user=flask_login.current_user)

main/routes/login.py
import ast
import json

import requests
from flask import Blueprint, render_template, make_response, url_for
from flask import current_app, flash
from flask_login import login_required, logout_user
from flask_login import login_user
from main.forms.login import Login, Register
from main.resources.auth import LoggedUser
from werkzeug.utils import redirect

login = Blueprint('login', __name__, url_prefix='/')


@login.route('/', methods=['POST', 'GET'])
def index():
    form_login = Login()
    if form_login.validate_on_submit():
        url = str(current_app.config['API_URL']) + str('/auth/login')

        data = '{"email":"' + form_login.email.data + \
               '", "password":"' + form_login.password.data + '"}'

        r = requests.post(url=url, headers={'content-type': 'application/json'}, data=data)

        if r.status_code == 200:
            user_json = json.loads(r.text)
            logged_user = LoggedUser(
                id=user_json['id'],
                admin=user_json['admin']
            )
            login_user(logged_user)
            if ast.literal_eval(user_json['admin']) == True:
                req = make_response(redirect(url_for('index.index')))
                req.set_cookie('access_token', user_json['access_token'], httponly=True)
                return req
            else:
                req = make_response(redirect(url_for('index.index')))
                req.set_cookie('access_token', user_json['access_token'], httponly=True)
                return req
        else:
            flash("Credenciales desconocidas. Por favor intente nuevamente.", 'danger')
        return redirect(url_for('login.index'))

    web = current_app.config['WEB_URL']

    return render_template('login.html',
                           form_login=form_login,
                           web=web)

@login.route('/register', methods=['POST', 'GET'])
def register():
    form = Register()
    if form.validate_on_submit():
        data = {
            "email": form.email.data,
            "password": form.password.data,
            "admin": form.admin.data
        }
        r = requests.post(current_app.config['API_URL'] + "/auth/register",
                          headers={'content-type': 'application/json'}, json=data)
        if r.status_code == 201:
            return redirect(url_for('login.index'))
        else:
            print("Error")
    return render_template('register.html', form=form)

@login.route('/logout')
@login_required
def logout():
    req = make_response(redirect(url_for('login.index')))
    req.set_cookie('access_token', '', httponly=True)
    logout_user()
    return req

main/templates/capture-location.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Capturando coordenadas</title>
</head>
<body>
    <form id="get-location" action="{{ url_for('index.index') }}" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <input type='hidden' id="location" name='location' style="{display: none;}"/>
        <input type='hidden' value='' style="{display: none;}"/>
    </form>
    <script type="text/javascript">
    var latlongvalue = "";
    function showLocation(position) {
    const {latitude, longitude} = position.coords;
    latlongvalue = `${latitude},${longitude}`;
    document.getElementById('location').value = latlongvalue;
    document.getElementById("get-location").submit();
    }
    function errorHandler(err) {
    if(err.code == 1) {
      alert("Error: Debes aceptar los permisos");
    } else if( err.code == 2) {
      alert("Error: La ubicacion no está disponible");
    }
    }
    function getLocation(){
    if(navigator.geolocation){
      var options = {timeout:60000};
      navigator.geolocation.getCurrentPosition(showLocation, errorHandler, options);
    } else{
      alert("Lo lamento, tu navegador no soporta geolocalización");
    }
    }
    getLocation();
    </script>
</body>
</html>

main/templates/config-parking.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Parkiing</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="static/vendors/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="static/vendors/base/vendor.bundle.base.css">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="static/css/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="static/images/favicon.png" />
</head>

<body>
  <div class="container-scroller">
    <!-- partial:static/partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="navbar-brand-wrapper d-flex justify-content-center">
        <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
          <a class="navbar-brand brand-logo" href="/index"><img src="static/images/logo.svg" alt="logo"/></a>
          <a class="navbar-brand brand-logo-mini" href="/index"><img src="static/images/logo-mini.svg" alt="logo"/></a>
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-sort-variant"></span>
          </button>
        </div>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <ul class="navbar-nav mr-lg-4 w-100">
          <li class="nav-item nav-search d-none d-lg-block w-100">
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text" id="search">
                  <i class="mdi mdi-magnify"></i>
                </span>
              </div>
              <input type="text" class="form-control" placeholder="Buscar" aria-label="search" aria-describedby="search">
            </div>
          </li>
        </ul>
        <ul class="navbar-nav navbar-nav-right">

          <li class="nav-item nav-profile dropdown">
            <a class="nav-link dropdown-toggle" href="static/#" data-bs-toggle="dropdown" id="profileDropdown">
              <img src="static/images/faces/face1.jpg" alt="profile"/>
              <span class="nav-profile-name">Usuario {{ current_user.id }}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
              <a href="/config" class="dropdown-item">
                <i class="mdi mdi-settings text-primary"></i>
                Configuraciones
              </a>
              <a href="/logout" class="dropdown-item">
                <i class="mdi mdi-logout text-primary"></i>
                Salir
              </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:static/partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="/index">
              <i class="mdi mdi-home menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/config">
              <i class="mdi mdi-settings menu-icon"></i>
              <span class="menu-title">Configuraciones</span>
            </a>
          </li>
        </ul>
      </nav>
      <!-- partial -->
      <div class="main-panel">        
        <div class="content-wrapper">
          <div class="row">

            <div class="col-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Basic form elements</h4>
                  <p class="card-description">
                    Basic form elements
                  </p>
                  <form class="forms-sample">
                    <div class="form-group">
                      <label for="exampleInputName1">Name</label>
                      <input type="text" class="form-control" id="exampleInputName1" placeholder="Name">
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail3">Email address</label>
                      <input type="email" class="form-control" id="exampleInputEmail3" placeholder="Email">
                    </div>
                    <div class="form-group">
                      <label for="exampleInputPassword4">Password</label>
                      <input type="password" class="form-control" id="exampleInputPassword4" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <label for="exampleSelectGender">Gender</label>
                        <select class="form-control" id="exampleSelectGender">
                          <option>Male</option>
                          <option>Female</option>
                        </select>
                      </div>
                    <div class="form-group">
                      <label>File upload</label>
                      <input type="file" name="img[]" class="file-upload-default">
                      <div class="input-group col-xs-12">
                        <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Image">
                        <span class="input-group-append">
                          <button class="file-upload-browse btn btn-primary" type="button">Upload</button>
                        </span>
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="exampleInputCity1">City</label>
                      <input type="text" class="form-control" id="exampleInputCity1" placeholder="Location">
                    </div>
                    <div class="form-group">
                      <label for="exampleTextarea1">Textarea</label>
                      <textarea class="form-control" id="exampleTextarea1" rows="4"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary me-2">Submit</button>
                    <button class="btn btn-light">Cancel</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:static/partials/_footer.html -->
        <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
          <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © Parkiing 2022</span>
        </div>
        </footer>
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="static/vendors/base/vendor.bundle.base.js"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="static/js/off-canvas.js"></script>
  <script src="static/js/hoverable-collapse.js"></script>
  <script src="static/js/template.js"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="static/js/file-upload.js"></script>
  <!-- End custom js for this page-->
</body>

</html>

main/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

main/templates/form_macros.html
{% macro show_error(field) %} {% if field.errors %}
{% for error in field.errors %} {{ error }}
{% endfor %}
{% endif %} {% endmacro %} {% macro show_field(field) %} {{ field.label }} {{ field(**kwargs)|safe }} {{show_error(field)}} {% endmacro %} {% macro show_submit(field) %} {{ field(**kwargs)|safe }} {% endmacro %} 

main/templates/macros.html
{% macro show_parkings(parking) %}
<tr onclick="window.location='http://google.com'">
    <td>{{parking.name}}</td>
    <td>{{parking.space}}</td>
    <td>{{parking.rate}}</td>
    <td>{{parking.price}}</td>
</tr>
{% endmacro %}

{% macro show_markers(parking) %}
    {% set lat, lon = parking.location.split(',') %}
    markers.addLayer(L.marker(["{{ lat }}", "{{ lon }}"], {icon: L.AwesomeMarkers.icon({})}).bindTooltip('{{parking.name}}', {permanent: false, className: 'my-label', offset: [0, 0] }));
{% endmacro %}

main/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Parkiing</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="static/vendors/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="static/vendors/base/vendor.bundle.base.css">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="static/css/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="static/images/favicon.png" />
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo">
                <img src="static/images/logo.svg" alt="logo">
              </div>
              <h4>¿Nuevo por aqui?</h4>
              <h6 class="font-weight-light">Inicia sesion y comienza a utilizar el servicio de manera simple y sencilla.</h6>
              {% block form %}
              <form class="pt-3" action="{{ url_for('login.register') }}" method="POST">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <div class="form-group">
                  {{ form.email(class_="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                  {{ form.re_email(class_="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                  {{ form.password(class_="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                  {{ form.re_password(class_="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                  ¿Desea administrar una playa de estacionamiento?
                </div>
                <div class="form-group">
                  {{ form.admin(class_="form-check-label") }}
                </div>
                <div class="mb-4">
                  <div class="form-check">
                    <label class="form-check-label text-muted">
                      <input type="checkbox" class="form-check-input" required>
                      Aceptar los términos y condiciones
                    </label>
                  </div>
                </div>
                <div class="mt-3">
                  {{ form.submit_button(class_="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn") }}
                </div>
                <div class="text-center mt-4 font-weight-light">
                  ¿Ya tienes una cuenta? <a href="/" class="text-primary">Ingresar</a>
                </div>
              </form>
              {% endblock %}
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="static/vendors/base/vendor.bundle.base.js"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="static/js/off-canvas.js"></script>
  <script src="static/js/hoverable-collapse.js"></script>
  <script src="static/js/template.js"></script>
  <!-- endinject -->
</body>

</html>

main/templates/setup.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Parkiing</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="static/vendors/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="static/vendors/base/vendor.bundle.base.css">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="static/css/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="static/images/favicon.png" />
</head>

<body>
  <div class="container-scroller">
    <!-- partial:static/partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="navbar-brand-wrapper d-flex justify-content-center">
        <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
          <a class="navbar-brand brand-logo" href="/index"><img src="static/images/logo.svg" alt="logo"/></a>
          <a class="navbar-brand brand-logo-mini" href="/index"><img src="static/images/logo-mini.svg" alt="logo"/></a>
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-sort-variant"></span>
          </button>
        </div>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <ul class="navbar-nav mr-lg-4 w-100">
          <li class="nav-item nav-search d-none d-lg-block w-100">
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text" id="search">
                  <i class="mdi mdi-magnify"></i>
                </span>
              </div>
              <input type="text" class="form-control" placeholder="Buscar" aria-label="search" aria-describedby="search">
            </div>
          </li>
        </ul>
        <ul class="navbar-nav navbar-nav-right">

          <li class="nav-item nav-profile dropdown">
            <a class="nav-link dropdown-toggle" href="static/#" data-bs-toggle="dropdown" id="profileDropdown">
              <img src="static/images/faces/face1.jpg" alt="profile"/>
              <span class="nav-profile-name">Usuario {{ current_user.id }}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
              <a href="/config" class="dropdown-item">
                <i class="mdi mdi-settings text-primary"></i>
                Configuraciones
              </a>
              <a href="/logout" class="dropdown-item">
                <i class="mdi mdi-logout text-primary"></i>
                Salir
              </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:static/partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="/index">
              <i class="mdi mdi-home menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/config">
              <i class="mdi mdi-settings menu-icon"></i>
              <span class="menu-title">Configuraciones</span>
            </a>
          </li>
        </ul>
      </nav>
      <!-- partial -->
      <div class="main-panel">        
        <div class="content-wrapper">
          <div class="row">

            <div class="col-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Configurar playa de estacionamiento</h4>
                  <p class="card-description">
                    Introduzca los datos necesarios, luego puede modificarlos.
                  </p>
                  <form class="forms-sample" action="{{ url_for('config.index') }}" method="POST">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <div class="form-group">
                      <label>Nombre</label>
                      {{ form_setup.name(class_="form-control") }}
                    </div>
                    <div class="form-group">
                      <label>Ubicacion</label>
                      {{ form_setup.location(class_="form-control") }}
                      <button type="button" onclick="getLocation();" class="btn btn-primary me-2">Geolocalizar</button>
                    </div>
                    <div class="form-group">
                      <label>Cantidad de espacios disponibles</label>
                      {{ form_setup.space(class_="form-control") }}
                    </div>
                    <div class="form-group">
                      <label>Precio</label>
                      {{ form_setup.price(class_="form-control") }}
                    </div>
                    {{ form_setup.submit_button(class_="btn btn-primary me-2") }}
                    <button class="btn btn-light">Cancelar</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:static/partials/_footer.html -->
        <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
          <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © Parkiing 2022</span>
        </div>
        </footer>
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="static/vendors/base/vendor.bundle.base.js"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="static/js/off-canvas.js"></script>
  <script src="static/js/hoverable-collapse.js"></script>
  <script src="static/js/template.js"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script type="text/javascript">
    function showLocation(position) {
      const {latitude, longitude} = position.coords;
      const latlongvalue = `${latitude},${longitude}`;
      var input = document.getElementById('location');
      input.value = latlongvalue;
    }
    function errorHandler(err) {
      if(err.code == 1) {
        alert("Error: Debes aceptar los permisos");
      } else if( err.code == 2) {
        alert("Error: La ubicacion no está disponible");
      }
    }
    function getLocation(){
      if(navigator.geolocation){
        var options = {timeout:60000};
        navigator.geolocation.getCurrentPosition(showLocation, errorHandler, options);
      } else{
        alert("Lo lamento, tu navegador no soporta geolocalización");
      }
    }
  </script>
  <script src="static/js/file-upload.js"></script>
  <!-- End custom js for this page-->
</body>

</html>